# Instance types
ENDPOINT_TYPE: m4.2xlarge
RDS_TYPE: db.t2.medium
REDIS_CACHE_TYPE: cache.m4.10xlarge
REDIS_TYPE: cache.m4.xlarge
CACHE_MANAGER_TYPE: t2.medium
ACTIVITIES_TYPE: m4.xlarge

# Cluster / ASG sizes
AUTH_CLUSTER_SIZE: 1
CONSUL_CLUSTER_SIZE: 5
VAULT_CLUSTER_SIZE: 3
ENDPOINT_CLUSTER_MIN: 1
ENDPOINT_CLUSTER_MAX: 20
REDIS_CLUSTER_SIZE: 2

# Memory Size
REDIS_RESERVED_MEM: 38500
