# Instance types
ENDPOINT_TYPE: m5.2xlarge
RDS_TYPE: db.t2.medium
REDIS_CACHE_TYPE: cache.m4.2xlarge
REDIS_SESSION_TYPE: cache.t2.medium
REDIS_TYPE: cache.m5.xlarge
CACHE_MANAGER_TYPE: t2.medium
VAULT_TYPE: m5.large
ACTIVITIES_TYPE: r5.xlarge
AUTH_TYPE: m5.xlarge

# Cluster / ASG sizes
AUTH_CLUSTER_SIZE: 1
VAULT_CLUSTER_SIZE: 1
ENDPOINT_CLUSTER_MIN: 1
ENDPOINT_CLUSTER_MAX: 60
REDIS_CLUSTER_SIZE: 2

# Memory Size
REDIS_RESERVED_MEMORY_PERCENT: 25
