#!/usr/bin/env python3

import sys
import ast

if len(sys.argv) != 2:
    print("Usage: {} <filter>".format(sys.argv[0]))
    print("       Data is read from stdin")
    sys.exit(1)

filter = sys.argv[1]
data = sys.stdin.read()
data = ast.literal_eval(data) # convert to python object in a safe maner without invoking json parsing

i = 0

def _min(a, b, d):
    if a == -1:
        return b if b != -1 else d
    elif b == -1:
        return a if a != -1 else d
    else:
        return min(a, b)

while i < len(filter):
    if filter[i] == '.':
        i += 1
    elif filter[i] == '[':
        j = filter.index(']', i)
        k = filter[i+1:j]
        i = j + 1
        try:
            data = data[int(k)]
        except:
            data = data[k]
    else:
        j = filter.find('[', i)
        j_ = filter.find('.', i)
        j = _min(j, j_, len(filter))
        k = filter[i:j]
        i = j + 1
        data = data[k]

print(data)
