#! /usr/bin/env bash
# sets up virtualenv, virtualwrapper,

cd /home/ec2-user
sudo yum groupinstall -y "Development Tools"

sudo yum install -y python34.x86_64 python34-devel.x86_64
curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
sudo python3 get-pip.py
sudo python3 -m pip install virtualenv
 
#sudo alternatives --set python /usr/bin/python3.4
#sudo pip install --upgrade pip

sudo yum install -y libjpeg-turbo-devel.x86_64 zlib-devel.x86_64 libtiff-devel.x86_64 freetype.x86_64 lcms2-devel.x86_64 libwebp-devel.x86_64 openjpeg-devel.x86_64

# needed for BLAS
sudo yum install -y atlas atlas-devel lapack-devel blas-devel

#virtualenv lambdaenv -p /usr/bin/python3.4

#sudo pip install virtualenvwrapper

mkdir ~/sitezips
mkdir ~/lambdazips
mkdir ~/debug
mkdir ~/virtualenvs

#export WORKON_HOME=~/virtualenvs
#echo export WORKON_HOME=~/virtualenvs >> /home/ec2-user/.bashrc
#export VIRTUALENVWRAPPER_PYTHON='/usr/bin/python' # This needs to be placed before the virtualenvwrapper command
#echo export VIRTUALENVWRAPPER_PYTHON=\'/usr/bin/python\' >> /home/ec2-user/.bashrc
#source /usr/local/bin/virtualenvwrapper.sh
#echo source /usr/local/bin/virtualenvwrapper.sh >> /home/ec2-user/.bashrc


